import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/date_symbol_data_local.dart';
import 'package:intl/intl.dart';

import 'core/constants/app_constants.dart';
import 'core/errors/error_boundary.dart';
import 'core/telemetry/telemetry.dart';
import 'firebase/firebase_init.dart';
import 'providers/auth_providers.dart';
import 'providers/subscription_providers.dart';
import 'providers/theme_provider.dart';
import 'routes/app_router.dart';
import 'services/connectivity_service.dart';
import 'theme/app_theme.dart';
import 'widgets/app_lock_gate.dart';
import 'widgets/async_value_view.dart';

Future<void> main() async {
  // runZonedGuarded is not used: PlatformDispatcher.onError (wired in
  // Telemetry.initialise) catches uncaught async errors on modern Flutter, and
  // wrapping ensureInitialized in a custom zone breaks binding assumptions.
  WidgetsFlutterBinding.ensureInitialized();

  // Locale data so DateFormat works for en_GB (dd/MM/yyyy etc.).
  await initializeDateFormatting();
  Intl.defaultLocale = AppConstants.defaultLocale;

  // Firebase + Firestore offline persistence.
  await FirebaseInit.ensureInitialized();

  // Crash reporting and analytics. Must come after Firebase.
  await Telemetry.initialise();

  // Replace the red screen of death with something a user can act on.
  ErrorBoundary.install();

  // Portrait-only: every screen is a single scrolling column, and landscape
  // buys nothing on a phone while doubling the layouts to verify.
  await SystemChrome.setPreferredOrientations(<DeviceOrientation>[
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  Telemetry.logEvent(AppEvent.appOpened);

  runApp(const ProviderScope(child: BuilderCrmApp()));
}

/// Root widget. Shows a splash until the first auth state is known, then hands
/// off to the go_router-driven navigation.
class BuilderCrmApp extends ConsumerWidget {
  const BuilderCrmApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final ThemeMode themeMode = ref.watch(themeModeProvider);
    final auth = ref.watch(authStateProvider);

    // Keep telemetry identity in step with auth, without a separate listener
    // widget. ref.listen inside build is the documented Riverpod pattern.
    ref.listen(currentUidProvider, (String? _, String? uid) {
      Telemetry.setUser(uid);
    });
    ref.listen(currentTierProvider, (previous, next) {
      Telemetry.setTier(next.id);
    });

    // While Firebase resolves the initial auth state, show a branded splash so
    // no protected screen builds before we know who (if anyone) is signed in.
    if (auth.isLoading) {
      return MaterialApp(
        debugShowCheckedModeBanner: false,
        theme: AppTheme.light(),
        darkTheme: AppTheme.dark(),
        themeMode: themeMode,
        home: const _Splash(),
      );
    }

    final router = ref.watch(routerProvider);
    return MaterialApp.router(
      title: AppConstants.appName,
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light(),
      darkTheme: AppTheme.dark(),
      themeMode: themeMode,
      routerConfig: router,
      builder: (BuildContext context, Widget? child) {
        // Order matters: the lock sits outermost so nothing behind it renders
        // until the user authenticates; the offline banner sits inside it.
        return AppLockGate(
          child: _ConnectivityShell(child: child ?? const SizedBox.shrink()),
        );
      },
    );
  }
}

/// Adds the offline banner above the routed content.
class _ConnectivityShell extends ConsumerWidget {
  const _ConnectivityShell({required this.child});
  final Widget child;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final bool offline = ref.watch(isOfflineProvider);
    return Column(
      children: <Widget>[
        AnimatedSize(
          duration: const Duration(milliseconds: 200),
          curve: Curves.easeOut,
          child: offline ? const OfflineBanner() : const SizedBox.shrink(),
        ),
        Expanded(child: child),
      ],
    );
  }
}

class _Splash extends StatelessWidget {
  const _Splash();

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            Image.asset(
              'assets/images/brand_mark.png',
              width: 96,
              height: 96,
              // The asset is generated by the build; if it is ever missing the
              // splash must still render rather than throwing.
              errorBuilder: (_, __, ___) => Container(
                width: 88,
                height: 88,
                decoration: BoxDecoration(
                  color: theme.colorScheme.primaryContainer,
                  borderRadius: BorderRadius.circular(24),
                ),
                child: Icon(Icons.handyman_rounded,
                    size: 46, color: theme.colorScheme.onPrimaryContainer),
              ),
            ),
            const SizedBox(height: 24),
            Text(
              AppConstants.appName,
              style: theme.textTheme.titleLarge
                  ?.copyWith(fontWeight: FontWeight.w700),
            ),
            const SizedBox(height: 24),
            const SizedBox(
              width: 26,
              height: 26,
              child: CircularProgressIndicator(strokeWidth: 2.6),
            ),
          ],
        ),
      ),
    );
  }
}
