import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'core/bootstrap.dart';
import 'core/constants/app_constants.dart';
import 'core/telemetry/telemetry.dart';
import 'providers/auth_providers.dart';
import 'providers/subscription_providers.dart';
import 'providers/theme_provider.dart';
import 'routes/app_router.dart';
import 'services/connectivity_service.dart';
import 'theme/app_theme.dart';
import 'widgets/app_lock_gate.dart';
import 'widgets/async_value_view.dart';

Future<void> main() async {
  // runZonedGuarded is not used: PlatformDispatcher.onError (wired in
  // Telemetry.initialise) catches uncaught async errors on modern Flutter, and
  // wrapping ensureInitialized in a custom zone breaks binding assumptions.
  WidgetsFlutterBinding.ensureInitialized();
  await _start();
}

/// Boots the app, or shows why it could not boot.
///
/// Kept as its own function so the failure screen's Retry button can run the
/// whole sequence again: calling `runApp` a second time swaps the root widget,
/// which is exactly what should happen after, say, turning airplane mode off.
Future<void> _start() async {
  final StartupFailure? failure = await Bootstrap.run();
  runApp(
    failure == null
        ? const ProviderScope(child: BuilderCrmApp())
        : _StartupFailureApp(failure: failure, onRetry: _start),
  );
}

/// Root widget. Shows a splash until the first auth state is known, then hands
/// off to the go_router-driven navigation.
class BuilderCrmApp extends ConsumerWidget {
  const BuilderCrmApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final ThemeMode themeMode = ref.watch(themeModeProvider);
    final auth = ref.watch(authStateProvider);

    // Keep telemetry identity in step with auth, without a separate listener
    // widget. ref.listen inside build is the documented Riverpod pattern.
    ref.listen<String?>(currentUidProvider, (String? _, String? uid) {
      Telemetry.setUser(uid);
    });
    ref.listen(currentTierProvider, (previous, next) {
      Telemetry.setTier(next.id);
    });

    // While Firebase resolves the initial auth state, show a branded splash so
    // no protected screen builds before we know who (if anyone) is signed in.
    if (auth.isLoading) {
      return MaterialApp(
        debugShowCheckedModeBanner: false,
        theme: AppTheme.light(),
        darkTheme: AppTheme.dark(),
        themeMode: themeMode,
        home: const _Splash(),
      );
    }

    final router = ref.watch(routerProvider);
    return MaterialApp.router(
      title: AppConstants.appName,
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light(),
      darkTheme: AppTheme.dark(),
      themeMode: themeMode,
      routerConfig: router,
      builder: (BuildContext context, Widget? child) {
        // Order matters: the lock sits outermost so nothing behind it renders
        // until the user authenticates; the offline banner sits inside it.
        return AppLockGate(
          child: _ConnectivityShell(child: child ?? const SizedBox.shrink()),
        );
      },
    );
  }
}

/// Adds the offline banner above the routed content.
class _ConnectivityShell extends ConsumerWidget {
  const _ConnectivityShell({required this.child});
  final Widget child;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final bool offline = ref.watch(isOfflineProvider);
    return Column(
      children: <Widget>[
        AnimatedSize(
          duration: const Duration(milliseconds: 200),
          curve: Curves.easeOut,
          child: offline ? const OfflineBanner() : const SizedBox.shrink(),
        ),
        Expanded(child: child),
      ],
    );
  }
}

class _Splash extends StatelessWidget {
  const _Splash();

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            Image.asset(
              'assets/images/brand_mark.png',
              width: 96,
              height: 96,
              // The asset is generated by the build; if it is ever missing the
              // splash must still render rather than throwing.
              errorBuilder: (_, __, ___) => Container(
                width: 88,
                height: 88,
                decoration: BoxDecoration(
                  color: theme.colorScheme.primaryContainer,
                  borderRadius: BorderRadius.circular(24),
                ),
                child: Icon(Icons.handyman_rounded,
                    size: 46, color: theme.colorScheme.onPrimaryContainer),
              ),
            ),
            const SizedBox(height: 24),
            Text(
              AppConstants.appName,
              style: theme.textTheme.titleLarge
                  ?.copyWith(fontWeight: FontWeight.w700),
            ),
            const SizedBox(height: 24),
            const SizedBox(
              width: 26,
              height: 26,
              child: CircularProgressIndicator(strokeWidth: 2.6),
            ),
          ],
        ),
      ),
    );
  }
}

/// Shown when startup could not finish.
///
/// The alternative is the Android launch icon sitting there indefinitely, with
/// no way to tell a broken build from a slow one. [StartupFailure.detail] is
/// deliberately on screen and selectable: on a phone with no cable attached it
/// is usually the only diagnostic anyone will ever get.
class _StartupFailureApp extends StatefulWidget {
  const _StartupFailureApp({required this.failure, required this.onRetry});

  final StartupFailure failure;
  final Future<void> Function() onRetry;

  @override
  State<_StartupFailureApp> createState() => _StartupFailureAppState();
}

class _StartupFailureAppState extends State<_StartupFailureApp> {
  bool _retrying = false;

  Future<void> _retry() async {
    setState(() => _retrying = true);
    await widget.onRetry();
    // A successful retry calls runApp again, which replaces this widget and
    // leaves this State defunct — so check before touching it.
    if (mounted) setState(() => _retrying = false);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light(),
      darkTheme: AppTheme.dark(),
      home: Builder(
        builder: (BuildContext context) {
          final ThemeData theme = Theme.of(context);
          return Scaffold(
            body: SafeArea(
              child: Center(
                child: SingleChildScrollView(
                  padding: const EdgeInsets.all(32),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    children: <Widget>[
                      const Icon(
                        Icons.cloud_off_rounded,
                        size: 52,
                        color: Color(0xFFA9700A),
                      ),
                      const SizedBox(height: 20),
                      Text(
                        '${AppConstants.appName} could not start',
                        textAlign: TextAlign.center,
                        style: theme.textTheme.titleLarge
                            ?.copyWith(fontWeight: FontWeight.w700),
                      ),
                      const SizedBox(height: 10),
                      Text(
                        widget.failure.timedOut
                            ? 'The app could not reach its database. Check '
                                'your internet connection, then try again.'
                            : 'Something went wrong while setting the app up. '
                                'Your data is safe.',
                        textAlign: TextAlign.center,
                        style: theme.textTheme.bodyMedium?.copyWith(
                          color: theme.colorScheme.onSurfaceVariant,
                        ),
                      ),
                      const SizedBox(height: 28),
                      FilledButton.icon(
                        onPressed: _retrying ? null : _retry,
                        icon: _retrying
                            ? const SizedBox(
                                width: 16,
                                height: 16,
                                child:
                                    CircularProgressIndicator(strokeWidth: 2),
                              )
                            : const Icon(Icons.refresh),
                        label: Text(_retrying ? 'Trying again' : 'Try again'),
                      ),
                      const SizedBox(height: 32),
                      Container(
                        width: double.infinity,
                        padding: const EdgeInsets.all(12),
                        decoration: BoxDecoration(
                          color: theme.colorScheme.surfaceContainerHighest,
                          borderRadius: BorderRadius.circular(10),
                        ),
                        child: SelectableText(
                          widget.failure.detail,
                          style: TextStyle(
                            fontSize: 12,
                            height: 1.4,
                            color: theme.colorScheme.onSurfaceVariant,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ),
          );
        },
      ),
    );
  }
}
